language: perl6
sudo: false
perl6:
  - latest
  - '2020.02.1'
before_install:
  - sudo apt-get -y install libharfbuzz-dev
  - sudo apt-get -y install libfribidi-dev
install:
  - rakudobrew build zef
  - zef --depsonly install .
script:
  - prove -ve "raku -I."
  - zef install .
