name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macOS-latest
          #- windows-latest
        raku-version:
          - 'latest'
          - '2021.10'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Library Dependencies
        run: |
          sudo apt-get install -y libfribidi-dev
          wget https://github.com/harfbuzz/harfbuzz/archive/3.3.1.tar.gz
          (tar xzf 3.3.1.tar.gz && cd harfbuzz-3.3.1 && ./autogen.sh && make && sudo make install)
          sudo ldconfig
      - name: Install Raku Dependencies
        run: |
          zef install --/test App::Prove6
          zef --deps-only install .
      - name: Run Tests
        run: |
          prove6 -I. t
          zef install .
