name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          #- windows-latest
        raku-version:
          - 'latest'
          - '2023.02'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Linux specific setup
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get install -y libfribidi-dev
      - name: macOS specific setup
        if: contains(matrix.os, 'macOS')
        run: |
          brew update
          brew install harfbuzz
          brew install fribidi
      - name: Install Raku Dependencies
        run: |
          zef install --/test App::Prove6
          zef --deps-only install .
      - name: Run Tests
        run: |
          prove6 -I. t
          zef install .
