name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macOS-latest
          #- windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Library Dependencies
        run: |
          sudo apt-get install -y libfribidi-dev
          wget https://github.com/harfbuzz/harfbuzz/archive/2.7.4.tar.gz
          (tar xzf 2.7.4.tar.gz && cd harfbuzz-2.7.4 && ./autogen.sh && make && sudo make install)
      - name: Install Raku Dependencies
        run: |
          export LD_LIBRARY_PATH=harfbuzz-2.7.4/src/.libs
          zef install --/test App::Prove6
          git clone https://github.com/harfbuzz-raku/Text-FriBidi-raku.git
          (cd Text-FriBidi-raku/ && zef install .)
          zef --deps-only install .
      - name: Run Tests
        run: |
          export LD_LIBRARY_PATH=harfbuzz-2.7.4/src/.libs
          prove6 -l t
          zef install .
